USE grouping_uth;
GO

CREATE TABLE PHONGBAN (
    TenPhong VARCHAR(15) NOT NULL,
    MaPhong INT NOT NULL,
    SoCCCD_TruongPhong CHAR(9) NULL, 
    NgayNhanChuc SMALLDATETIME,
    SoLuongNhanVien INT,
    CONSTRAINT PK_PHONGBAN PRIMARY KEY (MaPhong)
);

CREATE TABLE NHANVIEN (
    TenLot VARCHAR(15) NOT NULL,
    ChuCaiDauGiua CHAR(1),
    Ten VARCHAR(15) NOT NULL,
    SoCCCD CHAR(9) NOT NULL,
    NgaySinh SMALLDATETIME NULL,
    DiaChi VARCHAR(30),
    GioiTinh CHAR(1),
    Luong DECIMAL(18,2),
    SoCCCD_NguoiQL CHAR(9),
    MaPhong INT NOT NULL,
    NgayVaoLam SMALLDATETIME NULL,
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (SoCCCD),
    CONSTRAINT FK_NHANVIEN_NHANVIEN FOREIGN KEY (SoCCCD_NguoiQL) REFERENCES NHANVIEN (SoCCCD),
    CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY (MaPhong) REFERENCES PHONGBAN (MaPhong)
);


ALTER TABLE PHONGBAN
ADD CONSTRAINT FK_PHONGBAN_NHANVIEN FOREIGN KEY (SoCCCD_TruongPhong) REFERENCES NHANVIEN (SoCCCD)
ON DELETE CASCADE ON UPDATE CASCADE;


CREATE TABLE DUAN (
    TenDuAn VARCHAR(15) NOT NULL,
    SoDuAn INT NOT NULL,
    DiaDiemDuAn VARCHAR(15),
    MaPhong INT NOT NULL,
    CONSTRAINT PK_DUAN PRIMARY KEY (SoDuAn),
    CONSTRAINT FK_DUAN_PHONGBAN FOREIGN KEY (MaPhong) REFERENCES PHONGBAN (MaPhong)
);

CREATE TABLE DIADIEM_PHONG (
    MaPhong INT NOT NULL,
    DiaDiem VARCHAR(15) NOT NULL,
    CONSTRAINT PK_DIADIEM_PHONG PRIMARY KEY (MaPhong, DiaDiem),
    CONSTRAINT FK_DIADIEM_PHONG_PHONGBAN FOREIGN KEY (MaPhong) REFERENCES PHONGBAN (MaPhong)
);

CREATE TABLE NGUOI_PHU_THUOC (
    SoCCCD_NV CHAR(9) NOT NULL,
    TenNguoiPhuThuoc VARCHAR(15) NOT NULL,
    GioiTinh CHAR(1),
    NgaySinh SMALLDATETIME NULL,
    QuanHe VARCHAR(8),
    CONSTRAINT PK_NGUOI_PHU_THUOC PRIMARY KEY (SoCCCD_NV, TenNguoiPhuThuoc),
    CONSTRAINT FK_NGUOI_PHU_THUOC_NHANVIEN FOREIGN KEY (SoCCCD_NV) REFERENCES NHANVIEN (SoCCCD)
);

CREATE TABLE THAM_GIA (
    SoCCCD_NV CHAR(9) NOT NULL,
    SoDuAn INT NOT NULL,
    SoGio DECIMAL(18,1) NOT NULL,
    CONSTRAINT PK_THAM_GIA PRIMARY KEY (SoCCCD_NV, SoDuAn),
    CONSTRAINT FK_THAM_GIA_NHANVIEN FOREIGN KEY (SoCCCD_NV) REFERENCES NHANVIEN (SoCCCD),
    CONSTRAINT FK_THAM_GIA_DUAN FOREIGN KEY (SoDuAn) REFERENCES DUAN (SoDuAn)
);